ApiBundle\Entity\LogActivity:
    type: entity
    table: log_activity
    indexes:
        fk_log_activity_list_idx:
            columns:
                - list_id
        fk_log_activity_task_idx:
            columns:
                - task_id
        fk_log_activity_type_activity_idx:
            columns:
                - type_activity_id
        fk_log_activity_user_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        datetimeActivity:
            type: datetime
            nullable: false
            column: datetime_activity
    manyToOne:
        list:
            targetEntity: List
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                list_id:
                    referencedColumnName: id
            orphanRemoval: false
        task:
            targetEntity: Task
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                task_id:
                    referencedColumnName: id
            orphanRemoval: false
        typeActivity:
            targetEntity: TypeActivity
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_activity_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
