ApiBundle\Entity\Notification:
    type: entity
    table: notification
    indexes:
        fk_notification_user_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        message:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        readAt:
            type: datetime
            nullable: true
            column: read_at
    manyToOne:
        user:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
