ApiBundle\Entity\Team:
    type: entity
    table: team
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        archived:
            type: boolean
            nullable: true
            options:
                default: '0'
    lifecycleCallbacks: {  }
