users : 
  type: rest
  resource: "ManagileApiBundle:UserRest"
  name_prefix: api_

team :
  type: rest
  resource: "ManagileApiBundle:TeamRest"
  name_prefix: api_

teamRole :
  type: rest
  resource: "ManagileApiBundle:TeamRoleRest"
  name_prefix: api_

member :
  type: rest
  resource: "ManagileApiBundle:MemberRest"
  name_prefix: api_

board :
  type: rest
  resource: "ManagileApiBundle:BoardRest"
  name_prefix: api_

taskList :
  type: rest
  resource: "ManagileApiBundle:TaskListRest"
  name_prefix: api_

task :
  type: rest
  resource: "ManagileApiBundle:TaskRest"
  name_prefix: api_