managile_oauth_server_auth_login:
    pattern:    /oauth/v2/auth_login
    defaults: { _controller: ManagileOAuthBundle:OAuth:login }

managile_server_auth_login_check:
    path:    /oauth/v2/auth_login_check
    defaults: { _controller: ManagileOAuthBundle:OAuth:loginCheck }