Managile\ApiBundle\Entity\Board:
    type: entity
    table: board
    repositoryClass: Managile\ApiBundle\Entity\BoardRepository
    indexes:
        fk_board_team_idx:
            columns:
                - team_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        favorite:
            type: boolean
            nullable: true
            options:
                default: false
        archived:
            type: boolean
            nullable: true
            options:
                default: false
    manyToOne:
        team:
            targetEntity: Team
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                team_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
