Managile\ApiBundle\Entity\Checklist:
    type: entity
    table: checklist
    indexes:
        fk_checklist_task_idx:
            columns:
                - task_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tittle:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
        creationDate:
            type: datetime
            nullable: false
            column: creation_date
    manyToOne:
        task:
            targetEntity: Task
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                task_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
