Managile\ApiBundle\Entity\FosUser:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
