Managile\ApiBundle\Entity\LabeledTask:
    type: entity
    table: labeled_task
    indexes:
        fk_label_task_task_idx:
            columns:
                - task_id
        fk_labeled_task_label_idx:
            columns:
                - label_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        label:
            targetEntity: Label
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                label_id:
                    referencedColumnName: id
            orphanRemoval: false
        task:
            targetEntity: Task
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                task_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
